### ISSUE TITLE
Concurrency and memory considerations

### ISSUE THREAD

**Issue by joyoon** [crexi-dev/rate-limiter#20]
Should the design take concurrency into consideration?  (i.e., multiple threads simultaneously accessing the same object).  I'm assuming memory should be taken into consideration since this is a high load scenario.

**Comment by sviataslau** [comment]
Yes, concurrency should be taken into consideration at some basic level (e.g. if you have shared request log which is accessible from multiple locations).

As for the memory considerations, just use reasonable in-memory data structures, and it would be fine. For the request log, for instance, do not care about flushing the data to some persistent storage to free up memory, etc. We always can dive deeper here when discussing the code moving forward. 

This task has been mostly intended to give us an example of your thoughts when designing classes, data structures and tests rather than high-load systems, so feel free to keep it simple :)
