### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by aiodintsov** [crexi-dev/rate-limiter#248]
When it says:

> We're more interested in the design itself than in some intelligent and tricky rate-limiting algorithm...

Does it mean "design of the rule configuration classes" or "design of the implementation (such as efficient rule-matching against endpoints and context data and concurrent and safe rule execution"

That is how important it is choose and provide rule configuration classes, since a large part of usability of such library is an approach to configuring the rate limit rules, which also greatly depends on a way application is configured which may use xml, json, yaml, ini, custom configuration file and a range of other techniques which may become quite sophisticated really quickly, while still being irrelevant to the implementation; at the same time rule combinations are tightly coupled to rules configuration and definition approach.

Is there a suggestion on a specific rule definition / rule definition discovery format?

I.e. when defining WebApi endpoints (most natural use case for .NET / C# library) defining them with AOP attributes on the WebApi methods would probably be the easiest to use while offering either static or runtime discovery of the rules. However it also says that there is no need to add ASP.NET project, meaning that it should be configurable without it.

**Comment by rgarf81** [comment]
The reason we say _no need to add ASP.NET project_ is moreso to avoid having a lot of the PR adding controllers/endpoints. In modern times, we'd add https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-8.0 and be on our way. However, you can add that if you want, because you are correct, it's the most natural use case for this test.

> Does it mean "design of the rule configuration classes" or "design of the implementation (such as efficient rule-matching against endpoints and context data and concurrent and safe rule execution"

The latter. While you shouldn't ignore the configuration as it's an important piece without ASP.NET there to add attributes as you mentioned, once you have a resource and 1:M rate limit rules, how do you handle it is the design we are interested in.
